/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaConexion.Conexion;
import CapaDatos.EntradaProducto;
import CapaDatos.Venta;
import CapaNegocios.VentaBD;
import CapaNegocios.CompraBD;
import CapaNegocios.DetalleCajaBD;
import CapaNegocios.DetalleVentaBD;
import CapaNegocios.EntradaProductoBD;
import CapaNegocios.KardexBD;
import static CapaPresentacion.Venta_IU.tabla_ventas;
import static CapaPresentacion.Venta_IU.txtSubTotal;
import static CapaPresentacion.Venta_IU.txtTotalPagar;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Saucedo
 */
public class AnularVenta_IU extends javax.swing.JInternalFrame {

    DefaultTableModel tabla_temporal, tabla_temporal_entradaproducto, tabla_temporal_ventas;
    int idventa;
    String documento, correlativo, fecha, tienda;

    /**
     * Creates new form AnularVenta
     */
    public AnularVenta_IU() {
        initComponents();
    }

    private void limpiar() {
        txtCliente.setText("");
        txtFecha.setText("");
        txtHora.setText("");
        txtIgv.setText("");
        txtSubTotal.setText("");
        txtTipoPago.setText("");
        txtTotalPagar.setText("");
        txtCliente.setText("");
        txtEstado.setText("");

    }

    private void exito(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "MENSAJE", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
    }

    private void error(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "ERROR", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
    }

    private void advertencia(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "ADVERTENCIA", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
    }

    private void limpiar_tabla_formulario() {
        tabla_temporal_ventas = (DefaultTableModel) tabla_reporte_venta.getModel();
        tabla_temporal_ventas.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbDocumento = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtCorrelativo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dcFecha = new com.toedter.calendar.JDateChooser();
        btnBuscarVenta = new javax.swing.JButton();
        btnImprimirVoucher = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtRuc_Dni = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTipoPago = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        btnAnular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_reporte_venta = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIgv = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPagocon = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtVuelto = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("ANULAR VENTA");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la Busqueda"));

        jLabel1.setText("DOCUMENTO");

        cmbDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOLETA", "FACTURA" }));
        cmbDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbDocumentoKeyPressed(evt);
            }
        });

        jLabel2.setText("CORRELATIVO");

        txtCorrelativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorrelativoKeyPressed(evt);
            }
        });

        jLabel3.setText("FECHA");

        btnBuscarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/drive_magnify.png"))); // NOI18N
        btnBuscarVenta.setText("BUSCAR");
        btnBuscarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVentaActionPerformed(evt);
            }
        });

        btnImprimirVoucher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/impresora1.png"))); // NOI18N
        btnImprimirVoucher.setText("IMPRIMIR VOUCHER");
        btnImprimirVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirVoucherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCorrelativo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnBuscarVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImprimirVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscarVenta)
                        .addComponent(btnImprimirVoucher))
                    .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cmbDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtCorrelativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la Venta"));

        jLabel4.setText("FECHA");

        jLabel5.setText("RUC");

        txtFecha.setEnabled(false);

        txtRuc_Dni.setEnabled(false);

        txtHora.setEnabled(false);

        jLabel6.setText("HORA");

        jLabel7.setText("CLIENTE");

        txtCliente.setEnabled(false);

        jLabel8.setText("TIPO DE PAGO");

        txtTipoPago.setEnabled(false);

        jLabel9.setText("ESTADO");

        txtEstado.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRuc_Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtCliente))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRuc_Dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/page_delete.png"))); // NOI18N
        btnAnular.setText("ANULAR");
        btnAnular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnular.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });

        tabla_reporte_venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SERIE", "PRODUCTO", "CANT", "MEDIDA", "PRECIO", "DESCUENTO", "IMPORTE", "IDEP"
            }
        ));
        jScrollPane1.setViewportView(tabla_reporte_venta);
        if (tabla_reporte_venta.getColumnModel().getColumnCount() > 0) {
            tabla_reporte_venta.getColumnModel().getColumn(1).setPreferredWidth(400);
        }

        jLabel10.setText("SUB TOTAL");

        txtSubTotal.setEnabled(false);

        jLabel11.setText("IGV");

        txtIgv.setEnabled(false);

        jLabel12.setText("TOTAL A PAGAR");

        txtTotalPagar.setEnabled(false);

        jLabel13.setText("PAGO CON");

        txtPagocon.setEnabled(false);

        jLabel14.setText("VUELTO");

        txtVuelto.setEnabled(false);

        jLabel15.setText("USUARIO");

        txtUsuario.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAnular))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIgv, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPagocon, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(txtIgv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(txtPagocon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(txtVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVentaActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");
        limpiar_tabla_formulario();

        if (txtCorrelativo.getText().length() > 0) {
            if (dcFecha.getDate() != null) {

                documento = cmbDocumento.getSelectedItem().toString();
                correlativo = txtCorrelativo.getText().trim();
                fecha = dcn.format(dcFecha.getDate());
                VentaBD oVentaBD = new VentaBD();
                tienda = Login_IU.tienda;
                tabla_temporal = oVentaBD.buscarVentaAnular(correlativo, documento, fecha, tienda);
                int cant = tabla_temporal.getRowCount();

                if (cant > 0) {

                    txtFecha.setText(tabla_temporal.getValueAt(0, 1).toString());
                    txtHora.setText(tabla_temporal.getValueAt(0, 2).toString());
                    txtTipoPago.setText(tabla_temporal.getValueAt(0, 5).toString());
                    txtRuc_Dni.setText(tabla_temporal.getValueAt(0, 14).toString());
                    txtCliente.setText(tabla_temporal.getValueAt(0, 15).toString());
                    txtSubTotal.setText(tabla_temporal.getValueAt(0, 9).toString());
                    txtIgv.setText(tabla_temporal.getValueAt(0, 10).toString());
                    txtTotalPagar.setText(tabla_temporal.getValueAt(0, 11).toString());
                    txtEstado.setText(tabla_temporal.getValueAt(0, 7).toString());
                    txtPagocon.setText(tabla_temporal.getValueAt(0, 12).toString());
                    txtVuelto.setText(tabla_temporal.getValueAt(0, 13).toString());
                    txtUsuario.setText(Login_IU.usuario);
                    idventa = Integer.parseInt(tabla_temporal.getValueAt(0, 0).toString());
                    DetalleVentaBD oDetalleventaBD = new DetalleVentaBD();
                    tabla_temporal = oDetalleventaBD.buscarDetalleVenta(idventa);
                    tabla_temporal_ventas = (DefaultTableModel) tabla_reporte_venta.getModel();
                    cant = tabla_temporal.getRowCount();

                    for (int i = 0; i < cant; i++) {

                        String serie = tabla_temporal.getValueAt(i, 1).toString();
                        String producto = tabla_temporal.getValueAt(i, 2).toString();
                        String cantidad = tabla_temporal.getValueAt(i, 3).toString();
                        String medida = tabla_temporal.getValueAt(i, 4).toString();
                        String precio = tabla_temporal.getValueAt(i, 5).toString();
                        String descuento = tabla_temporal.getValueAt(i, 6).toString();
                        String importe = tabla_temporal.getValueAt(i, 7).toString();
                        String idep = tabla_temporal.getValueAt(i, 8).toString();

                        Object[] data = {serie, producto, cantidad, medida, precio, descuento, importe, idep};
                        tabla_temporal_ventas.addRow(data);

                    }

                } else {
                    error("No se encontro datos...");
                    limpiar();
                }

            } else {
                advertencia("Seleccione una fecha...");
            }
        } else {
            advertencia("Ingrese el numero del documento.....");
            txtCorrelativo.requestFocus();
        }
    }//GEN-LAST:event_btnBuscarVentaActionPerformed

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
        // TODO add your handling code here:

        try {
            if (txtEstado.getText().equals("ATENDIDO")) {
                int aviso = JOptionPane.showConfirmDialog(rootPane, "Estas seguro(a) de anular la Venta...");

                if (aviso == 0) {
                    EntradaProducto oEP = new EntradaProducto();
                    EntradaProductoBD oEPBD = new EntradaProductoBD();
                    tabla_temporal_ventas = (DefaultTableModel) tabla_reporte_venta.getModel();
                    int cant = tabla_temporal_ventas.getRowCount();
                    for (int i = 0; i < cant; i++) {
                        int idep = Integer.parseInt(tabla_temporal_ventas.getValueAt(i, 7).toString());
                        tabla_temporal_entradaproducto = oEPBD.buscarProductoXid(idep);
                        String presentacion = tabla_temporal_entradaproducto.getValueAt(0, 9).toString();
                        String equivalencia = tabla_temporal_entradaproducto.getValueAt(0, 10).toString();
                        if (presentacion.equals(equivalencia)) {
                            int cantPedido = (int)Double.parseDouble(tabla_temporal_ventas.getValueAt(i, 2).toString());
                            int stockUnidadesBD = Integer.parseInt(tabla_temporal_entradaproducto.getValueAt(0, 13).toString());
                            double quedaEquivalencia = stockUnidadesBD +cantPedido;
                            oEP.setStockPresentacion(0);
                            oEP.setStockEquivalencia((int) quedaEquivalencia);
                            oEP.setIdep(idep);
                            oEPBD.actualizarStockProducto(oEP);
                        } else {
                            String medidaEscogidaVenta = tabla_temporal_ventas.getValueAt(i, 3).toString();
                            if (presentacion.equals(medidaEscogidaVenta)) {
                                int cantPedido = (int)Double.parseDouble(tabla_temporal_ventas.getValueAt(i, 2).toString());
                                double stockPresentacionBD = Double.parseDouble(tabla_temporal_entradaproducto.getValueAt(0, 12).toString());
                                double quedaPresentacion = stockPresentacionBD + cantPedido;
                                double ref = Double.parseDouble(tabla_temporal_entradaproducto.getValueAt(0, 21).toString());
                                double quedaEquivalencia = (quedaPresentacion * ref);

                                oEP.setStockPresentacion(quedaPresentacion);
                                oEP.setStockEquivalencia((int) quedaEquivalencia);
                                oEP.setIdep(idep);
                            } else {
                                int cantPedido = (int)Double.parseDouble(tabla_temporal_ventas.getValueAt(i, 2).toString());
                                int stockUnidadesBD = Integer.parseInt(tabla_temporal_entradaproducto.getValueAt(0, 13).toString());
                                double quedaEquivalencia = stockUnidadesBD + cantPedido;
                                double ref = Double.parseDouble(tabla_temporal_entradaproducto.getValueAt(0, 21).toString());
                                double stockQuedaPresentacion = (quedaEquivalencia / ref);

                                oEP.setStockPresentacion(stockQuedaPresentacion);
                                oEP.setStockEquivalencia((int) quedaEquivalencia);
                                oEP.setIdep(idep);
                            }

                            oEPBD.actualizarStockProducto(oEP);
                        }
                    }
                    Venta oVenta = new Venta();
                    VentaBD oVentaBD = new VentaBD();
                    oVenta.setvEstado("ANULADO");
                    oVenta.setIdventas(idventa);
                    oVentaBD.ActualizarEstadoVenta(oVenta);
                    DetalleCajaBD oDetalleCajaBD = new DetalleCajaBD();
                    oDetalleCajaBD.eliminarIngresoventa(idventa);
                    KardexBD oKardexBD = new KardexBD();
                    oKardexBD.eliminarVentaKardex(idventa);
                    limpiar();
                    limpiar_tabla_formulario();
                }
            } else {
                advertencia("No puedes anular la veta porque ya esta anulada");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnAnularActionPerformed

    private void btnImprimirVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirVoucherActionPerformed
        // TODO add your handling code here:

        try {
            Conexion msyql = new Conexion();
            Connection cn = msyql.conectar();

            JasperReport reporte = null;
            InputStream reportStream;

            String ruta = "/CapaPresentacion/Reportes/Imprimir_Documento.jarper";
            String logo = "/CapaPresenatcion/Imagenes/logo.jpg";

            Map parametro = new HashMap();
            parametro.clear();

            parametro.put("cliente", txtCliente.getText());
            parametro.put("dni_ruc", txtRuc_Dni.getText());
            parametro.put("comprobante", cmbDocumento.getSelectedItem());
            parametro.put("correlativo", txtCorrelativo.getText());
            parametro.put("tienda", Login_IU.tienda);
            parametro.put("fecha", txtFecha.getText());
            parametro.put("hora", txtHora.getText());
            parametro.put("tipo_pago", txtTipoPago.getText());
            parametro.put("sub_total", txtSubTotal.getText());
            parametro.put("igv", txtIgv.getText());
            parametro.put("total", txtTotalPagar.getText());
            parametro.put("pago_con", txtPagocon.getText());
            parametro.put("vuelto", txtVuelto.getText());
            parametro.put("usuario", Login_IU.usuario);
            parametro.put("id_venta", idventa);
            parametro.put("logo", this.getClass().getResourceAsStream(logo));

            reportStream = AnularVenta_IU.class.getResourceAsStream(ruta);
            reporte = (JasperReport) JRLoader.loadObject(reportStream);

            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, cn);
            JasperViewer jvmostrar = new JasperViewer(jprint, false);

            jvmostrar.setTitle("IMPRIMIR DOCUMENTO");
            jvmostrar.setVisible(true);
            jvmostrar.setExtendedState(6);

            jvmostrar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

            JasperPrintManager.printReport(jprint, true);

        } catch (Exception e) {
            e.printStackTrace();

        }

    }//GEN-LAST:event_btnImprimirVoucherActionPerformed

    private void cmbDocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbDocumentoKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() ==KeyEvent.VK_ENTER) {
            txtCorrelativo.requestFocus();
        }
    }//GEN-LAST:event_cmbDocumentoKeyPressed

    private void txtCorrelativoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorrelativoKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() ==KeyEvent.VK_ENTER) {
            dcFecha.requestFocus();
        }
    }//GEN-LAST:event_txtCorrelativoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnBuscarVenta;
    private javax.swing.JButton btnImprimirVoucher;
    private javax.swing.JComboBox<String> cmbDocumento;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_reporte_venta;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCorrelativo;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtIgv;
    private javax.swing.JTextField txtPagocon;
    private javax.swing.JTextField txtRuc_Dni;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTipoPago;
    private javax.swing.JTextField txtTotalPagar;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtVuelto;
    // End of variables declaration//GEN-END:variables
}
