/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaConexion.Conexion;
import CapaNegocios.VentaBD;
import CapaNegocios.DetalleVentaBD;
import static CapaPresentacion.Venta_IU.tabla_ventas;
import java.io.InputStream;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Saucedo
 */
public class ReportesVentasVarios_IU extends javax.swing.JInternalFrame {

    DefaultTableModel tabla_temporal_ventas, tabla_temporal_detalle_ventas;
    DefaultTableModel tabla_temporal;
    SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form ReportesVentasVarios_IU
     */
    public ReportesVentasVarios_IU() {
        initComponents();
    }

    private void exito(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "MENSAJE", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
    }

    private void error(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "ERROR", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
    }

    private void advertencia(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "ADVERTENCIA", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
    }

    private void limpiar_tabla_formulario() {
        tabla_temporal_ventas = (DefaultTableModel) tabla_reporte_ventas.getModel();
        tabla_temporal_ventas.setRowCount(0);
    }

    private double dineroRecaudado() {
        tabla_temporal_ventas = (DefaultTableModel) tabla_reporte_ventas.getModel();
        int maxPedidos = tabla_temporal_ventas.getRowCount();
        double total = 0;
        for (int i = 0; i < maxPedidos; i++) {
            total = total + Double.parseDouble(tabla_temporal_ventas.getValueAt(i, 4).toString());

        }
        return total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_reporte_ventas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_reporte_detalle_ventas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dcFechaInicioVentasAnuladas = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        dcFechaFinalVentasAnuladas = new com.toedter.calendar.JDateChooser();
        btnBuscarVentasAnuladas = new javax.swing.JButton();
        btnImprimirVentasAnuladas = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        dcFechaInicioVentasDocumento = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        dcFechaFinalVentasDocumentos = new com.toedter.calendar.JDateChooser();
        cmbDocumento = new javax.swing.JComboBox<>();
        btnBuscarVentasDocumentos = new javax.swing.JButton();
        btnImprimirVentasDocumentos = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtDineroRecaudadoDocumento = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        dcFechaInicioVentasContador = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        dcFechaFinalVentasContado = new com.toedter.calendar.JDateChooser();
        btnBuscarVentasContado = new javax.swing.JButton();
        btnImprimirVentaContado = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtDineroRecaudadoVentasContado = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("REPORTES DE VENTAS");

        tabla_reporte_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDVENTA", "CLIENTE", "DOCUMENTO", "CORRELATIVO", "TOTAL", "FECHA", "ESTADO"
            }
        ));
        tabla_reporte_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_reporte_ventasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_reporte_ventas);
        if (tabla_reporte_ventas.getColumnModel().getColumnCount() > 0) {
            tabla_reporte_ventas.getColumnModel().getColumn(1).setPreferredWidth(350);
        }

        tabla_reporte_detalle_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla_reporte_detalle_ventas);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("DETALLE DE LA VENTA...");

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/cross.png"))); // NOI18N
        btnCerrar.setText("CERRAR");
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setText("FECHA INICIO");

        dcFechaInicioVentasAnuladas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dcFechaInicioVentasAnuladasFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                dcFechaInicioVentasAnuladasFocusGained(evt);
            }
        });
        dcFechaInicioVentasAnuladas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcFechaInicioVentasAnuladasKeyPressed(evt);
            }
        });

        jLabel4.setText("FECHA FINAL");

        dcFechaFinalVentasAnuladas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dcFechaFinalVentasAnuladasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dcFechaFinalVentasAnuladasFocusLost(evt);
            }
        });
        dcFechaFinalVentasAnuladas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcFechaFinalVentasAnuladasKeyPressed(evt);
            }
        });

        btnBuscarVentasAnuladas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/date_magnify.png"))); // NOI18N
        btnBuscarVentasAnuladas.setText("BUSCAR");
        btnBuscarVentasAnuladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVentasAnuladasActionPerformed(evt);
            }
        });

        btnImprimirVentasAnuladas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/impresora1.png"))); // NOI18N
        btnImprimirVentasAnuladas.setText("IMPRIMIR");
        btnImprimirVentasAnuladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirVentasAnuladasActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/eliminar2.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dcFechaInicioVentasAnuladas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dcFechaFinalVentasAnuladas, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarVentasAnuladas)
                .addGap(39, 39, 39)
                .addComponent(btnImprimirVentasAnuladas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 594, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dcFechaInicioVentasAnuladas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dcFechaFinalVentasAnuladas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarVentasAnuladas, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(btnImprimirVentasAnuladas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("VENTAS ANULADAS", jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel9.setText("FECHA INICIO");

        dcFechaInicioVentasDocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dcFechaInicioVentasDocumentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dcFechaInicioVentasDocumentoFocusLost(evt);
            }
        });
        dcFechaInicioVentasDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcFechaInicioVentasDocumentoKeyPressed(evt);
            }
        });

        jLabel10.setText("FECHA FINAL");

        dcFechaFinalVentasDocumentos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dcFechaFinalVentasDocumentosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dcFechaFinalVentasDocumentosFocusLost(evt);
            }
        });
        dcFechaFinalVentasDocumentos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcFechaFinalVentasDocumentosKeyPressed(evt);
            }
        });

        cmbDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "BOLETA ", "FACTURA" }));
        cmbDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbDocumentoKeyPressed(evt);
            }
        });

        btnBuscarVentasDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/lupa.gif"))); // NOI18N
        btnBuscarVentasDocumentos.setText("BUSCAR");
        btnBuscarVentasDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVentasDocumentosActionPerformed(evt);
            }
        });

        btnImprimirVentasDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/impresora1.png"))); // NOI18N
        btnImprimirVentasDocumentos.setText("IMPRIMIR");
        btnImprimirVentasDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirVentasDocumentosActionPerformed(evt);
            }
        });

        jLabel11.setText("DINERO RECAUDADO");

        txtDineroRecaudadoDocumento.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dcFechaInicioVentasDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dcFechaFinalVentasDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarVentasDocumentos)
                .addGap(26, 26, 26)
                .addComponent(btnImprimirVentasDocumentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDineroRecaudadoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dcFechaInicioVentasDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dcFechaFinalVentasDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarVentasDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnImprimirVentasDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(txtDineroRecaudadoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("VENTAS X DOCUMENTOS", jPanel1);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel6.setText("FECHA INICIO");

        dcFechaInicioVentasContador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dcFechaInicioVentasContadorFocusGained(evt);
            }
        });
        dcFechaInicioVentasContador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcFechaInicioVentasContadorKeyPressed(evt);
            }
        });

        jLabel7.setText("FECHA FINAL");

        dcFechaFinalVentasContado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcFechaFinalVentasContadoKeyPressed(evt);
            }
        });

        btnBuscarVentasContado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/icons8-buscar-cliente-48.png"))); // NOI18N
        btnBuscarVentasContado.setText("BUSCAR");
        btnBuscarVentasContado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVentasContadoActionPerformed(evt);
            }
        });

        btnImprimirVentaContado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/impresora1.png"))); // NOI18N
        btnImprimirVentaContado.setText("IMPRIMIR");
        btnImprimirVentaContado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirVentaContadoActionPerformed(evt);
            }
        });

        jLabel8.setText("DINERO RECAUDADO");

        txtDineroRecaudadoVentasContado.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dcFechaInicioVentasContador, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dcFechaFinalVentasContado, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnBuscarVentasContado)
                .addGap(36, 36, 36)
                .addComponent(btnImprimirVentaContado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 372, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDineroRecaudadoVentasContado, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dcFechaInicioVentasContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dcFechaFinalVentasContado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarVentasContado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtDineroRecaudadoVentasContado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnImprimirVentaContado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("VENTAS AL CONTADO", jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("CLIENTE");

        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(937, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("VENTAS X CLIENTE", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(btnCerrar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabla_reporte_ventasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_reporte_ventasMousePressed
        // TODO add your handling code here:

        int fila_seleccionada = tabla_reporte_ventas.getSelectedRow();
        DetalleVentaBD oDetalleVentaBD = new DetalleVentaBD();

        int idventa = Integer.parseInt(tabla_temporal_ventas.getValueAt(fila_seleccionada, 0).toString());

        tabla_temporal_detalle_ventas = oDetalleVentaBD.buscarDetalleVenta(idventa);
        tabla_reporte_detalle_ventas.setModel(tabla_temporal_detalle_ventas);
    }//GEN-LAST:event_tabla_reporte_ventasMousePressed

    private void btnImprimirVentaContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirVentaContadoActionPerformed
        // TODO add your handling code here:
        try {
            Conexion msyql = new Conexion();
            Connection cn = msyql.conectar();

            if (dcFechaInicioVentasContador.getDate() != null) {
                if (dcFechaFinalVentasContado.getDate() != null) {

                    JasperReport reporte = null;
                    InputStream reportStream;

                    String ruta = "/CapaPresentacion/Reportes/Reporte_Ventas_Contado.jasper";

                    Map parametro = new HashMap();
                    parametro.clear();
                    parametro.put("fecha_inicio", dcn.format(dcFechaInicioVentasContador.getDate()));
                    parametro.put("fecha_final", dcn.format(dcFechaFinalVentasContado.getDate()));
                    parametro.put("tienda", Login_IU.tienda);

                    reportStream = ReportesVentasVarios_IU.class.getResourceAsStream(ruta);
                    reporte = (JasperReport) JRLoader.loadObject(reportStream);

                    JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, cn);
                    JasperViewer jvmostrar = new JasperViewer(jprint, false);

                    jvmostrar.setTitle("REPORTE DE VENTAS POR CONTADO");
                    jvmostrar.setVisible(true);
                    jvmostrar.setExtendedState(6);

                    jvmostrar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

                } else {
                    advertencia("Ingrese la fecha de inicio...");
                }
            } else {
                advertencia("Ingrese la fecha final...");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnImprimirVentaContadoActionPerformed

    private void btnBuscarVentasContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVentasContadoActionPerformed
        // TODO add your handling code here:
        try {
            limpiar_tabla_formulario();
            VentaBD oVenta = new VentaBD();

            if (dcFechaInicioVentasContador.getDate() != null) {
                if (dcFechaFinalVentasContado.getDate() != null) {

                    String fechaInicio = dcn.format(dcFechaInicioVentasContador.getDate());
                    String fechaFinal = dcn.format(dcFechaFinalVentasContado.getDate());
                   
                    String tienda = Login_IU.tienda;
                    tabla_temporal = oVenta.reportarVentaVarios(fechaInicio, fechaFinal,"CONTADO", "ATENDIDO", tienda);
                    int cant = tabla_temporal.getRowCount();

                    for (int i = 0; i < cant; i++) {

                        String id_venta = tabla_temporal.getValueAt(i, 0).toString();
                        String cliente = tabla_temporal.getValueAt(i, 15).toString();
                        String documento = tabla_temporal.getValueAt(i, 3).toString();
                        String correlativo = tabla_temporal.getValueAt(i, 4).toString();
                        String total_pagar = tabla_temporal.getValueAt(i, 11).toString();
                        String fecha = tabla_temporal.getValueAt(i, 1).toString();
                        tienda = tabla_temporal.getValueAt(i, 17).toString();
                        String estado = tabla_temporal.getValueAt(i, 7).toString();

                        Object[] data = {id_venta, cliente, documento, correlativo, total_pagar, fecha, estado};
                        tabla_temporal_ventas.addRow(data);

                    }
                    tabla_reporte_ventas.setModel(tabla_temporal_ventas);
                    double total = dineroRecaudado();
                    DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.ENGLISH);
                    DecimalFormat df = new DecimalFormat("#.#", symbols);
                    String df_total = df.format(total);
                    txtDineroRecaudadoVentasContado.setText(String.valueOf(df_total));

                } else {
                   JOptionPane.showMessageDialog(null, "Ingrese la fecha de final....");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese la fecha de inicio.... ");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnBuscarVentasContadoActionPerformed

    private void dcFechaFinalVentasContadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcFechaFinalVentasContadoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcFechaFinalVentasContadoKeyPressed

    private void dcFechaInicioVentasContadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcFechaInicioVentasContadorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcFechaInicioVentasContadorKeyPressed

    private void dcFechaInicioVentasContadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFechaInicioVentasContadorFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dcFechaInicioVentasContadorFocusGained

    private void btnImprimirVentasDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirVentasDocumentosActionPerformed
        // TODO add your handling code here:
        try {
            Conexion msyql = new Conexion();
            Connection cn = msyql.conectar();

            if (dcFechaInicioVentasDocumento.getDate() != null) {
                if (dcFechaFinalVentasDocumentos.getDate() != null) {

                    JasperReport reporte = null;
                    InputStream reportStream;

                    String ruta = "/CapaPresentacion/Reportes/Reportes_Ventas_Documentos.jasper";

                    Map parametro = new HashMap();
                    parametro.clear();
                    parametro.put("fecha_inicio", dcn.format(dcFechaInicioVentasDocumento.getDate()));
                    parametro.put("fecha_final", dcn.format(dcFechaFinalVentasDocumentos.getDate()));
                    parametro.put("documento", cmbDocumento.getSelectedItem());
                    parametro.put("tienda", Login_IU.tienda);

                    reportStream = ReportesVentasVarios_IU.class.getResourceAsStream(ruta);
                    reporte = (JasperReport) JRLoader.loadObject(reportStream);

                    JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, cn);
                    JasperViewer jvmostrar = new JasperViewer(jprint, false);

                    jvmostrar.setTitle("REPORTE DE VENTAS POR DOCUMENTOS");
                    jvmostrar.setVisible(true);
                    jvmostrar.setExtendedState(6);

                    jvmostrar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

                } else {
                    advertencia("Ingrese la fecha de inicio...");
                }
            } else {
                advertencia("Ingrese la fecha final...");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnImprimirVentasDocumentosActionPerformed

    private void btnBuscarVentasDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVentasDocumentosActionPerformed
        // TODO add your handling code here:
        try {
            limpiar_tabla_formulario();
            VentaBD oVenta = new VentaBD();

            if (dcFechaInicioVentasDocumento.getDate() != null) {
                if (dcFechaInicioVentasDocumento.getDate() != null) {

                    String fechaInicio = dcn.format(dcFechaInicioVentasDocumento.getDate());
                    String fechaFinal = dcn.format(dcFechaFinalVentasDocumentos.getDate());
                    String tienda = Login_IU.tienda;
                    tabla_temporal = oVenta.reportarVentaVarios(fechaInicio, fechaFinal, "CONTADO", "ATENDIDO", tienda);
                    int cant = tabla_temporal.getRowCount();

                    for (int i = 0; i < cant; i++) {

                        String id_venta = tabla_temporal.getValueAt(i, 0).toString();
                        String cliente = tabla_temporal.getValueAt(i, 15).toString();
                        String documento = tabla_temporal.getValueAt(i, 3).toString();
                        String correlativo = tabla_temporal.getValueAt(i, 4).toString();
                        String total_pagar = tabla_temporal.getValueAt(i, 11).toString();
                        String fecha = tabla_temporal.getValueAt(i, 1).toString();
                        tienda = tabla_temporal.getValueAt(i, 17).toString();
                        String estado = tabla_temporal.getValueAt(i, 7).toString();

                        Object[] data = {id_venta, cliente, documento, correlativo, total_pagar, fecha, estado};
                        tabla_temporal_ventas.addRow(data);

                    }
                    tabla_reporte_ventas.setModel(tabla_temporal_ventas);
                    double total = dineroRecaudado();
                    DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.ENGLISH);
                    DecimalFormat df = new DecimalFormat("#.#", symbols);
                    String df_total = df.format(total);
                    txtDineroRecaudadoVentasContado.setText(String.valueOf(df_total));

                } else {
                    advertencia("Ingrese la fecha de inicio...");
                }
            } else {
                advertencia("Ingrese la fecha final.....");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnBuscarVentasDocumentosActionPerformed

    private void cmbDocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbDocumentoKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbDocumentoKeyPressed

    private void dcFechaFinalVentasDocumentosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcFechaFinalVentasDocumentosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcFechaFinalVentasDocumentosKeyPressed

    private void dcFechaFinalVentasDocumentosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFechaFinalVentasDocumentosFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_dcFechaFinalVentasDocumentosFocusLost

    private void dcFechaFinalVentasDocumentosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFechaFinalVentasDocumentosFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dcFechaFinalVentasDocumentosFocusGained

    private void dcFechaInicioVentasDocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcFechaInicioVentasDocumentoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcFechaInicioVentasDocumentoKeyPressed

    private void dcFechaInicioVentasDocumentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFechaInicioVentasDocumentoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_dcFechaInicioVentasDocumentoFocusLost

    private void dcFechaInicioVentasDocumentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFechaInicioVentasDocumentoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dcFechaInicioVentasDocumentoFocusGained

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnImprimirVentasAnuladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirVentasAnuladasActionPerformed
        // TODO add your handling code here:

        try {
            Conexion msyql = new Conexion();
            Connection cn = msyql.conectar();

            if (dcFechaFinalVentasAnuladas.getDate() != null) {
                if (dcFechaInicioVentasAnuladas.getDate() != null) {

                    JasperReport reporte = null;
                    InputStream reportStream;

                    String ruta = "/CapaPresentacion/Reportes/Ventas_Anuladas.jasper";

                    Map parametro = new HashMap();
                    parametro.clear();
                    parametro.put("fecha_inicio", dcn.format(dcFechaInicioVentasAnuladas.getDate()));
                    parametro.put("fecha_final", dcn.format(dcFechaFinalVentasAnuladas.getDate()));
                    parametro.put("tienda", Login_IU.tienda);

                    reportStream = ReportesVentasVarios_IU.class.getResourceAsStream(ruta);
                    reporte = (JasperReport) JRLoader.loadObject(reportStream);

                    JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, cn);
                    JasperViewer jvmostrar = new JasperViewer(jprint, false);

                    jvmostrar.setTitle("REPORTE DE VENTAS ANULADAS");
                    jvmostrar.setVisible(true);
                    jvmostrar.setExtendedState(6);

                    jvmostrar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

                } else {
                    advertencia("Ingrese la fecha de inicio...");
                }
            } else {
                advertencia("Ingrese la fecha final...");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnImprimirVentasAnuladasActionPerformed

    private void btnBuscarVentasAnuladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVentasAnuladasActionPerformed
        // TODO add your handling code here:
        try {
            limpiar_tabla_formulario();
            VentaBD oVenta = new VentaBD();

            if (dcFechaFinalVentasAnuladas.getDate() != null) {
                if (dcFechaInicioVentasAnuladas.getDate() != null) {

                    String fechaInicio = dcn.format(dcFechaInicioVentasAnuladas.getDate());
                    String fechaFinal = dcn.format(dcFechaFinalVentasAnuladas.getDate());
                    String tienda = Login_IU.tienda;
                    tabla_temporal = oVenta.reportarVentaVarios(fechaInicio, fechaFinal, "CONTADO", "ANULADO", tienda);
                    int cant = tabla_temporal.getRowCount();

                    for (int i = 0; i < cant; i++) {

                        String id_venta = tabla_temporal.getValueAt(i, 0).toString();
                        String cliente = tabla_temporal.getValueAt(i, 15).toString();
                        String documento = tabla_temporal.getValueAt(i, 3).toString();
                        String correlativo = tabla_temporal.getValueAt(i, 4).toString();
                        String total_pagar = tabla_temporal.getValueAt(i, 11).toString();
                        String fecha = tabla_temporal.getValueAt(i, 1).toString();
                        String hora = tabla_temporal.getValueAt(i, 2).toString();
                        String pagoCon = tabla_temporal.getValueAt(i, 12).toString();
                        String vuelto = tabla_temporal.getValueAt(i, 13).toString();
                        String forma_pago = tabla_temporal.getValueAt(i, 6).toString();
                        String moneda = tabla_temporal.getValueAt(i, 8).toString();
                        String uDni = tabla_temporal.getValueAt(i, 16).toString();
                        tienda = tabla_temporal.getValueAt(i, 17).toString();
                        String estado = tabla_temporal.getValueAt(i, 7).toString();

                        Object[] data = {id_venta, cliente, documento, correlativo, total_pagar, fecha, estado};
                        tabla_temporal_ventas.addRow(data);

                    }
                    tabla_reporte_ventas.setModel(tabla_temporal_ventas);

                } else {
                    advertencia("Ingrese la fecha de inicio...");
                }
            } else {
                advertencia("Ingrese la fecha final.....");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnBuscarVentasAnuladasActionPerformed

    private void dcFechaFinalVentasAnuladasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcFechaFinalVentasAnuladasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcFechaFinalVentasAnuladasKeyPressed

    private void dcFechaFinalVentasAnuladasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFechaFinalVentasAnuladasFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_dcFechaFinalVentasAnuladasFocusLost

    private void dcFechaFinalVentasAnuladasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFechaFinalVentasAnuladasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dcFechaFinalVentasAnuladasFocusGained

    private void dcFechaInicioVentasAnuladasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcFechaInicioVentasAnuladasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcFechaInicioVentasAnuladasKeyPressed

    private void dcFechaInicioVentasAnuladasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFechaInicioVentasAnuladasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dcFechaInicioVentasAnuladasFocusGained

    private void dcFechaInicioVentasAnuladasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFechaInicioVentasAnuladasFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_dcFechaInicioVentasAnuladasFocusLost

    private void txtClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyReleased
        // TODO add your handling code here:
        try {
            limpiar_tabla_formulario();
            VentaBD oVenta = new VentaBD();
            String cliente = txtCliente.getText();
            String tienda = Login_IU.tienda;
            tabla_temporal = oVenta.reportarVentaCliente(cliente, tienda);
            int cant = tabla_temporal.getRowCount();
            for (int i = 0; i < cant; i++) {
                String id_venta = tabla_temporal.getValueAt(i, 0).toString();
                cliente = tabla_temporal.getValueAt(i, 15).toString();
                String documento = tabla_temporal.getValueAt(i, 3).toString();
                String correlativo = tabla_temporal.getValueAt(i, 4).toString();
                String total_pagar = tabla_temporal.getValueAt(i, 11).toString();
                String fecha = tabla_temporal.getValueAt(i, 1).toString();
                String estado = tabla_temporal.getValueAt(i, 7).toString();

                Object[] data = {id_venta, cliente, documento, correlativo, total_pagar, fecha, estado};
                tabla_temporal_ventas.addRow(data);

            }
            tabla_reporte_ventas.setModel(tabla_temporal_ventas);
            double total = dineroRecaudado();
            DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.ENGLISH);
            DecimalFormat df = new DecimalFormat("#.#", symbols);
            String df_total = df.format(total);
            txtDineroRecaudadoDocumento.setText(""+df_total);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtClienteKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarVentasAnuladas;
    private javax.swing.JButton btnBuscarVentasContado;
    private javax.swing.JButton btnBuscarVentasDocumentos;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnImprimirVentaContado;
    private javax.swing.JButton btnImprimirVentasAnuladas;
    private javax.swing.JButton btnImprimirVentasDocumentos;
    private javax.swing.JComboBox<String> cmbDocumento;
    private com.toedter.calendar.JDateChooser dcFechaFinalVentasAnuladas;
    private com.toedter.calendar.JDateChooser dcFechaFinalVentasContado;
    private com.toedter.calendar.JDateChooser dcFechaFinalVentasDocumentos;
    private com.toedter.calendar.JDateChooser dcFechaInicioVentasAnuladas;
    private com.toedter.calendar.JDateChooser dcFechaInicioVentasContador;
    private com.toedter.calendar.JDateChooser dcFechaInicioVentasDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabla_reporte_detalle_ventas;
    private javax.swing.JTable tabla_reporte_ventas;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDineroRecaudadoDocumento;
    private javax.swing.JTextField txtDineroRecaudadoVentasContado;
    // End of variables declaration//GEN-END:variables
}
