/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaConexion.Conexion;
import CapaNegocios.ColorearColumnasJTable;
import CapaNegocios.CompraBD;
import CapaNegocios.DetalleCompraBD;
import CapaNegocios.ProveedorBD;
import java.io.InputStream;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Saucedo
 */
public class ReporteComprasVarios_IU extends javax.swing.JInternalFrame {

    DefaultTableModel tabla_temporal_compras, tabla_temporal_detalle_compras;

    /**
     * Creates new form ReporteComprasVarios_IU
     */
    public ReporteComprasVarios_IU() {
        initComponents();
        cargarProveedores();

        ColorearColumnasJTable col5 = new ColorearColumnasJTable(5, Color.YELLOW);

        ColorearColumnasJTable col7 = new ColorearColumnasJTable(7, Color.PINK);

        tabla_reporte_compras.getColumnModel().getColumn(5).setCellRenderer(col5);
        tabla_reporte_compras.getColumnModel().getColumn(7).setCellRenderer(col7);
    }

    private void cargarProveedores() {
        try {
            cmbProveedor.removeAllItems();

            ProveedorBD oProveedorBD = new ProveedorBD();
            DefaultTableModel tabla_temporal;
            tabla_temporal = oProveedorBD.reportarProveedor();

            cmbProveedor.addItem("Seleccionar");

            for (int i = 0; i < tabla_temporal.getRowCount(); i++) {
                String proveedor = String.valueOf(tabla_temporal.getValueAt(i, 1));
                cmbProveedor.addItem(proveedor);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error al cargar proveedor", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiar_tabla_formulario() {
        tabla_temporal_compras = (DefaultTableModel) tabla_reporte_compras.getModel();
        tabla_temporal_compras.setRowCount(0);

        tabla_temporal_detalle_compras = (DefaultTableModel) tabla_reporte_detalle_compras.getModel();
        tabla_temporal_detalle_compras.setRowCount(0);

    }

    private double dineroGastado() {
        tabla_temporal_compras = (DefaultTableModel) tabla_reporte_compras.getModel();
        int maxPedidos = tabla_temporal_compras.getRowCount();
        double total = 0;
        for (int i = 0; i < maxPedidos; i++) {
            total = total + Double.parseDouble(tabla_temporal_compras.getValueAt(i, 8).toString());

        }
        return total;
    }

    private void advertencia(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "ADVERTENCIA", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dcFechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        dcFechaFinal = new com.toedter.calendar.JDateChooser();
        btnBuscarComprasFechas1 = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        dcFechaInicioDocumentos = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        dcFechaFinalDocumentos = new com.toedter.calendar.JDateChooser();
        cmbDocumento = new javax.swing.JComboBox<>();
        btnBuscarDocumentos = new javax.swing.JButton();
        btnImprimirDocumentos = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtTotalComprasDocumentos = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        dcFechaInicioProveedor = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        dcFechaFinalproveedor = new com.toedter.calendar.JDateChooser();
        btnBuscarComprasproveedor = new javax.swing.JButton();
        btnImprimirComprasProveedor = new javax.swing.JButton();
        cmbProveedor = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtTotalComprasProveedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_reporte_detalle_compras = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_reporte_compras = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setText("FECHA INICIO");

        dcFechaInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dcFechaInicioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dcFechaInicioFocusLost(evt);
            }
        });
        dcFechaInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcFechaInicioKeyPressed(evt);
            }
        });

        jLabel4.setText("FECHA FINAL");

        dcFechaFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dcFechaFinalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dcFechaFinalFocusLost(evt);
            }
        });
        dcFechaFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcFechaFinalKeyPressed(evt);
            }
        });

        btnBuscarComprasFechas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/date_magnify.png"))); // NOI18N
        btnBuscarComprasFechas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarComprasFechas1ActionPerformed(evt);
            }
        });

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/impresora1.png"))); // NOI18N
        btnImprimir.setText("IMPRIMIR");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/eliminar2.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dcFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarComprasFechas1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 515, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dcFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBuscarComprasFechas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("COMPRAS POR FECHA", jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel9.setText("FECHA INICIO");

        dcFechaInicioDocumentos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dcFechaInicioDocumentosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dcFechaInicioDocumentosFocusLost(evt);
            }
        });
        dcFechaInicioDocumentos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcFechaInicioDocumentosKeyPressed(evt);
            }
        });

        jLabel10.setText("FECHA FINAL");

        dcFechaFinalDocumentos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dcFechaFinalDocumentosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dcFechaFinalDocumentosFocusLost(evt);
            }
        });
        dcFechaFinalDocumentos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcFechaFinalDocumentosKeyPressed(evt);
            }
        });

        cmbDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "BOLETA ", "FACTURA" }));
        cmbDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbDocumentoKeyPressed(evt);
            }
        });

        btnBuscarDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/lupa.gif"))); // NOI18N
        btnBuscarDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDocumentosActionPerformed(evt);
            }
        });

        btnImprimirDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/impresora1.png"))); // NOI18N
        btnImprimirDocumentos.setText("IMPRIMIR");
        btnImprimirDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirDocumentosActionPerformed(evt);
            }
        });

        jLabel11.setText("TOTAL COMPRAS");

        txtTotalComprasDocumentos.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dcFechaInicioDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dcFechaFinalDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnImprimirDocumentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTotalComprasDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dcFechaInicioDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dcFechaFinalDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnImprimirDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(txtTotalComprasDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("COMPRAS POR DOCUMENTOS", jPanel1);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel6.setText("FECHA INICIO");

        dcFechaInicioProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dcFechaInicioProveedorFocusGained(evt);
            }
        });
        dcFechaInicioProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcFechaInicioProveedorKeyPressed(evt);
            }
        });

        jLabel7.setText("FECHA FINAL");

        dcFechaFinalproveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcFechaFinalproveedorKeyPressed(evt);
            }
        });

        btnBuscarComprasproveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/icons8-buscar-cliente-48.png"))); // NOI18N
        btnBuscarComprasproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarComprasproveedorActionPerformed(evt);
            }
        });

        btnImprimirComprasProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/impresora1.png"))); // NOI18N
        btnImprimirComprasProveedor.setText("IMPRIMIR");
        btnImprimirComprasProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirComprasProveedorActionPerformed(evt);
            }
        });

        cmbProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProveedorActionPerformed(evt);
            }
        });
        cmbProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbProveedorKeyPressed(evt);
            }
        });

        jLabel8.setText("TOTAL COMPRAS");

        txtTotalComprasProveedor.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dcFechaInicioProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dcFechaFinalproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarComprasproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnImprimirComprasProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTotalComprasProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dcFechaInicioProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dcFechaFinalproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarComprasproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtTotalComprasProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnImprimirComprasProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("COMPRAS POR PROVEEDOR", jPanel3);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("DETALLE DE LA COMPRA...");

        tabla_reporte_detalle_compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla_reporte_detalle_compras);

        tabla_reporte_compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDCOMPRA", "FECHA", "RUC", "PROVEEDOR", "DOCUMENTO", "CORRELATIVO", "TIPO PAGO", "FORMA PAGO", "TOTAL", "USUARIO", "TIENDA"
            }
        ));
        tabla_reporte_compras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_reporte_comprasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_reporte_compras);
        if (tabla_reporte_compras.getColumnModel().getColumnCount() > 0) {
            tabla_reporte_compras.getColumnModel().getColumn(3).setPreferredWidth(400);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarComprasFechas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarComprasFechas1ActionPerformed
        // TODO add your handling code here:
        try {
            limpiar_tabla_formulario();
            CompraBD oCompraBD = new CompraBD();
            SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");
            if (dcFechaFinal.getDate() != null) {
                if (dcFechaInicio.getDate() != null) {

                    setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
                    String fechaInicio = dcn.format(dcFechaInicio.getDate());
                    String fechaFinal = dcn.format(dcFechaFinal.getDate());

                    DefaultTableModel tabla_temporal;
                    tabla_temporal = oCompraBD.reportarComprasFechas(fechaInicio, fechaFinal);
                    int cant = tabla_temporal.getRowCount();

                    for (int i = 0; i < cant; i++) {

                        String idcompra = tabla_temporal.getValueAt(i, 0).toString();
                        String fecha = tabla_temporal.getValueAt(i, 1).toString();
                        String ruc = tabla_temporal.getValueAt(i, 12).toString();
                        String proveedor = tabla_temporal.getValueAt(i, 2).toString();
                        String documento = tabla_temporal.getValueAt(i, 3).toString();
                        String correlativo = tabla_temporal.getValueAt(i, 4).toString();
                        String tipo_pago = tabla_temporal.getValueAt(i, 5).toString();
                        String forma_pago = tabla_temporal.getValueAt(i, 6).toString();
                        String total = tabla_temporal.getValueAt(i, 11).toString();
                        String tienda = Login_IU.tienda;
                        String uDni = Login_IU.dni_publico;
                        Object[] data = {idcompra, fecha, ruc, proveedor, documento, correlativo, tipo_pago, forma_pago, total, uDni, tienda};
                        tabla_temporal_compras.addRow(data);

                    }
                    tabla_reporte_compras.setModel(tabla_temporal_compras);
                    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

                } else {
                    advertencia("Ingrese la fecha de inicio...");
                }
            } else {
                advertencia("Ingrese la fecha final.....");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnBuscarComprasFechas1ActionPerformed

    private void tabla_reporte_comprasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_reporte_comprasMousePressed
        // TODO add your handling code here:

        int fila_seleccionada = tabla_reporte_compras.getSelectedRow();
        DetalleCompraBD oDetalleCompraBD = new DetalleCompraBD();

        int idcompra = Integer.parseInt(tabla_temporal_compras.getValueAt(fila_seleccionada, 0).toString());

        tabla_temporal_detalle_compras = oDetalleCompraBD.buscarDetalleCompra(idcompra);
        tabla_reporte_detalle_compras.setModel(tabla_temporal_detalle_compras);
    }//GEN-LAST:event_tabla_reporte_comprasMousePressed

    private void btnBuscarDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDocumentosActionPerformed
        // TODO add your handling code here:
        try {
            limpiar_tabla_formulario();
            CompraBD oCompraBD = new CompraBD();
            SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");
            if (dcFechaInicioDocumentos.getDate() != null) {
                if (dcFechaFinalDocumentos.getDate() != null) {

                    setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
                    String fechaInicio = dcn.format(dcFechaInicioDocumentos.getDate());
                    String fechaFinal = dcn.format(dcFechaFinalDocumentos.getDate());
                    String documento = cmbDocumento.getSelectedItem().toString();

                    DefaultTableModel tabla_temporal;
                    tabla_temporal = oCompraBD.reportarCompraDocumentos(fechaInicio, fechaFinal, documento);
                    int cant = tabla_temporal.getRowCount();

                    for (int i = 0; i < cant; i++) {

                        String idcompra = tabla_temporal.getValueAt(i, 0).toString();
                        String fecha = tabla_temporal.getValueAt(i, 1).toString();
                        String ruc = tabla_temporal.getValueAt(i, 12).toString();
                        String proveedor = tabla_temporal.getValueAt(i, 2).toString();
                        documento = tabla_temporal.getValueAt(i, 3).toString();
                        String correlativo = tabla_temporal.getValueAt(i, 4).toString();
                        String tipo_pago = tabla_temporal.getValueAt(i, 5).toString();
                        String forma_pago = tabla_temporal.getValueAt(i, 6).toString();
                        String total = tabla_temporal.getValueAt(i, 11).toString();
                        String tienda = Login_IU.tienda;
                        String uDni = Login_IU.dni_publico;
                        Object[] data = {idcompra, fecha, ruc, proveedor, documento, correlativo, tipo_pago, forma_pago, total, uDni, tienda};
                        tabla_temporal_compras.addRow(data);

                    }
                    tabla_reporte_compras.setModel(tabla_temporal_compras);
                    double total_compras_documentos = dineroGastado();
                    BigDecimal numero = new BigDecimal(total_compras_documentos);
                    BigDecimal decimal_compra_documentos = numero.setScale(2, RoundingMode.DOWN);
                    txtTotalComprasDocumentos.setText("" + decimal_compra_documentos);
                    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

                } else {
                    advertencia("Ingrese la fecha final documentos...");
                }
            } else {
                advertencia("Ingrese la fecha de inicio documentos.....");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btnBuscarDocumentosActionPerformed

    private void cmbProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProveedorActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbProveedorActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        int fila_seleccionada = tabla_reporte_compras.getSelectedRow();

        if (fila_seleccionada > -1) {
            int aviso = JOptionPane.showConfirmDialog(rootPane, "Estas seguro de eliminar");
            if (aviso == 0) {

                CompraBD oCompraBD = new CompraBD();
                DetalleCompraBD oDetalleCompraBD = new DetalleCompraBD();

                int idcompra = Integer.parseInt(tabla_reporte_compras.getValueAt(fila_seleccionada, 0).toString());

                boolean rpta1 = oDetalleCompraBD.eliminarDetalleCompra(idcompra);
                boolean rpta = oCompraBD.eliminarCompra(idcompra);

                if (rpta) {
                    advertencia("Se elimino su compra...");
                    limpiar_tabla_formulario();
                } else {
                    advertencia("Tienes problemas al eliminar" + rpta + rpta1);
                }

            }
        } else {
            advertencia("Seleccione una fila para saber que compra quiere eliminar....");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarComprasproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarComprasproveedorActionPerformed
        // TODO add your handling code here:
        try {
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

            limpiar_tabla_formulario();
            CompraBD oCompraBD = new CompraBD();
            SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");
            if (dcFechaInicioProveedor.getDate() != null) {
                if (dcFechaFinalproveedor.getDate() != null) {

                    String fechaInicio = dcn.format(dcFechaInicioProveedor.getDate());
                    String fechaFinal = dcn.format(dcFechaFinalproveedor.getDate());
                    String proveedor = cmbProveedor.getSelectedItem().toString();

                    DefaultTableModel tabla_temporal;
                    tabla_temporal = oCompraBD.reportarCompraProveedor(fechaInicio, fechaFinal, proveedor);
                    int cant = tabla_temporal.getRowCount();

                    for (int i = 0; i < cant; i++) {

                        String idcompra = tabla_temporal.getValueAt(i, 0).toString();
                        String fecha = tabla_temporal.getValueAt(i, 1).toString();
                        String ruc = tabla_temporal.getValueAt(i, 12).toString();
                        proveedor = tabla_temporal.getValueAt(i, 2).toString();
                        String documento = tabla_temporal.getValueAt(i, 3).toString();
                        String correlativo = tabla_temporal.getValueAt(i, 4).toString();
                        String tipo_pago = tabla_temporal.getValueAt(i, 5).toString();
                        String forma_pago = tabla_temporal.getValueAt(i, 6).toString();
                        String total = tabla_temporal.getValueAt(i, 11).toString();
                        String tienda = Login_IU.tienda;
                        String uDni = Login_IU.dni_publico;
                        Object[] data = {idcompra, fecha, ruc, proveedor, documento, correlativo, tipo_pago, forma_pago, total, uDni, tienda};
                        tabla_temporal_compras.addRow(data);

                    }
                    tabla_reporte_compras.setModel(tabla_temporal_compras);
                    double total_compras_proveedor = dineroGastado();
                    BigDecimal numero = new BigDecimal(total_compras_proveedor);
                    BigDecimal decimal_compra_proveedor = numero.setScale(2, RoundingMode.DOWN);
                    txtTotalComprasProveedor.setText("" + decimal_compra_proveedor);
                    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

                } else {
                    advertencia("Ingrese la fecha final proveedor...");
                }
            } else {
                advertencia("Ingrese la fecha de inicio proveedor.....");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnBuscarComprasproveedorActionPerformed

    private void dcFechaInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFechaInicioFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_dcFechaInicioFocusGained

    private void dcFechaInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFechaInicioFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_dcFechaInicioFocusLost

    private void dcFechaFinalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFechaFinalFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_dcFechaFinalFocusGained

    private void dcFechaFinalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFechaFinalFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_dcFechaFinalFocusLost

    private void dcFechaInicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcFechaInicioKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_dcFechaInicioKeyPressed

    private void dcFechaFinalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcFechaFinalKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_dcFechaFinalKeyPressed

    private void dcFechaInicioDocumentosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFechaInicioDocumentosFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_dcFechaInicioDocumentosFocusGained

    private void dcFechaInicioDocumentosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFechaInicioDocumentosFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_dcFechaInicioDocumentosFocusLost

    private void dcFechaFinalDocumentosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFechaFinalDocumentosFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_dcFechaFinalDocumentosFocusGained

    private void dcFechaFinalDocumentosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFechaFinalDocumentosFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_dcFechaFinalDocumentosFocusLost

    private void dcFechaInicioDocumentosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcFechaInicioDocumentosKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_dcFechaInicioDocumentosKeyPressed

    private void dcFechaFinalDocumentosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcFechaFinalDocumentosKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_dcFechaFinalDocumentosKeyPressed

    private void cmbDocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbDocumentoKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {
            btnBuscarDocumentos.requestFocus();
            btnBuscarDocumentos.doClick();

        }
    }//GEN-LAST:event_cmbDocumentoKeyPressed

    private void dcFechaInicioProveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcFechaInicioProveedorFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_dcFechaInicioProveedorFocusGained

    private void dcFechaInicioProveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcFechaInicioProveedorKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_dcFechaInicioProveedorKeyPressed

    private void dcFechaFinalproveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcFechaFinalproveedorKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_dcFechaFinalproveedorKeyPressed

    private void cmbProveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbProveedorKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {
            btnBuscarComprasproveedor.requestFocus();
            btnBuscarComprasproveedor.doClick();

        }
    }//GEN-LAST:event_cmbProveedorKeyPressed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:

        try {
            Conexion msyql = new Conexion();
            Connection cn = msyql.conectar();

            SimpleDateFormat dcn = new SimpleDateFormat("yyy-MM-dd");

            if (dcFechaFinal.getDate() != null) {
                if (dcFechaInicio.getDate() != null) {

                    JasperReport reporte = null;
                    InputStream reportStream;

                    String ruta = "/CapaPresentacion/Reportes/Reporte_Compras_Fecha.jasper";

                    Map parametro = new HashMap();
                    parametro.clear();
                    parametro.put("Fecha_inicio", dcn.format(dcFechaInicio.getDate()));
                    parametro.put("Fecha_Final", dcn.format(dcFechaFinal.getDate()));

                    reportStream = ReporteComprasVarios_IU.class.getResourceAsStream(ruta);
                    reporte = (JasperReport) JRLoader.loadObject(reportStream);

                    JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, cn);
                    JasperViewer jvmostrar = new JasperViewer(jprint, false);

                    jvmostrar.setTitle("REPORTE DE COMPRAS POR FECHAS");
                    jvmostrar.setVisible(true);
                    jvmostrar.setExtendedState(6);

                    jvmostrar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

                } else {
                    advertencia("Ingrese la fecha de inicio...");
                }
            } else {
                advertencia("Ingrese la fecha final...");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnImprimirDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirDocumentosActionPerformed
        // TODO add your handling code here:
        try {
            Conexion msyql = new Conexion();
            Connection cn = msyql.conectar();

            SimpleDateFormat dcn = new SimpleDateFormat("yyy-MM-dd");
            if (!cmbDocumento.getSelectedItem().equals("Seleccionar")) {
                if (dcFechaFinalDocumentos.getDate() != null) {
                    if (dcFechaInicioDocumentos.getDate() != null) {

                        JasperReport reporte = null;
                        InputStream reportStream;

                        String ruta = "/CapaPresentacion/Reportes/Reporte_Compras_Documento.jasper";

                        Map parametro = new HashMap();
                        parametro.clear();
                        parametro.put("fecha_inicio", dcn.format(dcFechaInicioDocumentos.getDate()));
                        parametro.put("fecha_final", dcn.format(dcFechaFinalDocumentos.getDate()));
                        parametro.put("documento",(cmbDocumento.getSelectedItem()));

                        reportStream = ReporteComprasVarios_IU.class.getResourceAsStream(ruta);
                        reporte = (JasperReport) JRLoader.loadObject(reportStream);

                        JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, cn);
                        JasperViewer jvmostrar = new JasperViewer(jprint, false);

                        jvmostrar.setTitle("REPORTE DE COMPRAS POR DOCUMENTO");
                        jvmostrar.setVisible(true);
                        jvmostrar.setExtendedState(6);

                        jvmostrar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

                    } else {
                        advertencia("Ingrese la fecha de inicio...");
                    }
                } else {
                    advertencia("Ingrese la fecha final...");
                }
            } else {
                advertencia("Ingrese documento...");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnImprimirDocumentosActionPerformed

    private void btnImprimirComprasProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirComprasProveedorActionPerformed
        // TODO add your handling code here:
        try {
            Conexion msyql = new Conexion();
            Connection cn = msyql.conectar();

            SimpleDateFormat dcn = new SimpleDateFormat("yyy-MM-dd");
          
                if (dcFechaFinalproveedor.getDate() != null) {
                    if (dcFechaInicioProveedor.getDate() != null) {

                        JasperReport reporte = null;
                        InputStream reportStream;

                        String ruta = "/CapaPresentacion/Reportes/Reporte_Compras_Proveedor.jasper";

                        Map parametro = new HashMap();
                        parametro.clear();
                        parametro.put("fecha_inicio", dcn.format(dcFechaInicioProveedor.getDate()));
                        parametro.put("fecha_final", dcn.format(dcFechaFinalproveedor.getDate()));
                        parametro.put("proveedor",(cmbProveedor.getSelectedItem()));

                        reportStream = ReporteComprasVarios_IU.class.getResourceAsStream(ruta);
                        reporte = (JasperReport) JRLoader.loadObject(reportStream);

                        JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, cn);
                        JasperViewer jvmostrar = new JasperViewer(jprint, false);

                        jvmostrar.setTitle("REPORTE DE COMPRAS POR PROVEEDOR");
                        jvmostrar.setVisible(true);
                        jvmostrar.setExtendedState(6);

                        jvmostrar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

                    } else {
                        advertencia("Ingrese la fecha de inicio...");
                    }
                } else {
                    advertencia("Ingrese la fecha final...");
                }
           

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnImprimirComprasProveedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarComprasFechas1;
    private javax.swing.JButton btnBuscarComprasproveedor;
    private javax.swing.JButton btnBuscarDocumentos;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnImprimirComprasProveedor;
    private javax.swing.JButton btnImprimirDocumentos;
    private javax.swing.JComboBox<String> cmbDocumento;
    private javax.swing.JComboBox<String> cmbProveedor;
    private com.toedter.calendar.JDateChooser dcFechaFinal;
    private com.toedter.calendar.JDateChooser dcFechaFinalDocumentos;
    private com.toedter.calendar.JDateChooser dcFechaFinalproveedor;
    private com.toedter.calendar.JDateChooser dcFechaInicio;
    private com.toedter.calendar.JDateChooser dcFechaInicioDocumentos;
    private com.toedter.calendar.JDateChooser dcFechaInicioProveedor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabla_reporte_compras;
    private javax.swing.JTable tabla_reporte_detalle_compras;
    private javax.swing.JTextField txtTotalComprasDocumentos;
    private javax.swing.JTextField txtTotalComprasProveedor;
    // End of variables declaration//GEN-END:variables
}
