/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaConexion.Conexion;
import CapaDatos.TipoUsuario;
import CapaDatos.Usuario;
import CapaNegocios.AjustarColumnasJTable;
import CapaNegocios.TipoUsuarioBD;
import CapaNegocios.UsuarioBD;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Saucedo
 */
public class Usuario_IU extends javax.swing.JInternalFrame {
       List<TipoUsuario> lista_tipo_usuario;

    /**
     * Creates new form Usuario_IU
     */
    public Usuario_IU() {
        initComponents();
        cargarTipoUsuario();
        reportar_usuarios();
    }
     private void cargarTipoUsuario() {
        try {
            cmbTipoUsuario.removeAllItems();

            TipoUsuarioBD oMedidaBD = new TipoUsuarioBD();
            DefaultTableModel tabla_temporal;
            tabla_temporal = oMedidaBD.reportarTipoUsuario();

            lista_tipo_usuario = new ArrayList<>();
            cmbTipoUsuario.addItem("SELECCIONAR");

            for (int i = 0; i < tabla_temporal.getRowCount(); i++) {

                int idtipousuario = Integer.valueOf(tabla_temporal.getValueAt(i, 0).toString());
                String tuNombre = String.valueOf(tabla_temporal.getValueAt(i, 1));

                lista_tipo_usuario.add(new TipoUsuario(idtipousuario, tuNombre));
                cmbTipoUsuario.addItem(tuNombre);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "error al cargar tipo usuario", JOptionPane.ERROR_MESSAGE);
        }
     }
         private void reportar_usuarios() {
        try {
            setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
            DefaultTableModel tabla_temporal;
            UsuarioBD objeto_usuarioBD = new UsuarioBD();
            tabla_temporal = objeto_usuarioBD.reportarUsuarios();
            tabla_reporte_usuario.setModel(tabla_temporal);

            int cantLista = tabla_temporal.getRowCount();
            txtcantidad.setText("" + cantLista);

            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            
            tabla_reporte_usuario.setModel(tabla_temporal);
            AjustarColumnasJTable.ajustarAnchoColumnas(tabla_reporte_usuario);
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        } catch (Exception ex) {
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            ex.printStackTrace();
        }

     }
          private void limpiar() {
        txtdni.setText("");
        txtnombres.setText("");
        txtapellidos.setText("");
        txtdireccion.setText("");
        txtclave.setText("");
        txtbuscar_apellidos.setText("");
        txtcelular.setText("");
        txtId_TIPO_USUARIO.setText("");

        cmbTipoUsuario.setSelectedIndex(0);
    }

    private void exito(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "MENSAJE", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
    }

    private void error(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "ERROR", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
    }

    private void advertencia(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "ADVERTENCIA", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtclave = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcelular = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbTipoUsuario = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbTienda = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtbuscar_apellidos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_reporte_usuario = new javax.swing.JTable();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btncerrar = new javax.swing.JButton();
        btnimprimir = new javax.swing.JButton();
        txtId_TIPO_USUARIO = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        btnReportar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("USUARIO");

        jLabel1.setText("DNI");

        txtdni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdniFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdniFocusLost(evt);
            }
        });
        txtdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdniKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdniKeyTyped(evt);
            }
        });

        jLabel2.setText("NOMBRES");

        txtnombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnombresFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnombresFocusLost(evt);
            }
        });
        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombresKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresKeyTyped(evt);
            }
        });

        jLabel3.setText("APELLIDOS");

        txtapellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtapellidosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtapellidosFocusLost(evt);
            }
        });
        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtapellidosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidosKeyTyped(evt);
            }
        });

        jLabel4.setText("DIRECCION");

        txtdireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdireccionFocusLost(evt);
            }
        });
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdireccionKeyPressed(evt);
            }
        });

        jLabel5.setText("CLAVE");

        txtclave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtclaveFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtclaveFocusLost(evt);
            }
        });
        txtclave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtclaveKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtclaveKeyTyped(evt);
            }
        });

        jLabel6.setText("CELULAR");

        txtcelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcelularFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcelularFocusLost(evt);
            }
        });
        txtcelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcelularKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcelularKeyTyped(evt);
            }
        });

        jLabel7.setText("TIPO");

        cmbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoUsuarioItemStateChanged(evt);
            }
        });
        cmbTipoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbTipoUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbTipoUsuarioFocusLost(evt);
            }
        });
        cmbTipoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbTipoUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmbTipoUsuarioKeyTyped(evt);
            }
        });

        jLabel8.setText("TIENDA");

        cmbTienda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRINCIPAL" }));
        cmbTienda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbTiendaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbTiendaFocusLost(evt);
            }
        });
        cmbTienda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbTiendaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmbTiendaKeyTyped(evt);
            }
        });

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/disk.png"))); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel9.setText("BUSCAR APELLIDOS");

        txtbuscar_apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscar_apellidosActionPerformed(evt);
            }
        });
        txtbuscar_apellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscar_apellidosKeyPressed(evt);
            }
        });

        tabla_reporte_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_reporte_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_reporte_usuarioMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_reporte_usuario);

        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/report_edit.png"))); // NOI18N
        btnmodificar.setText("MODIFICAR");
        btnmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/bin_empty.png"))); // NOI18N
        btneliminar.setText("ELIMINAR");
        btneliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btneliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/cross.png"))); // NOI18N
        btncerrar.setText("CERRAR");
        btncerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        btnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/printer.png"))); // NOI18N
        btnimprimir.setText("IMPRIMIR");
        btnimprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnimprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        txtId_TIPO_USUARIO.setEnabled(false);

        jLabel10.setText("CANTIDAD");

        txtcantidad.setEnabled(false);
        txtcantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcantidadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcantidadFocusLost(evt);
            }
        });

        btnReportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/report_user.png"))); // NOI18N
        btnReportar.setText("REPORTAR");
        btnReportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdireccion)
                    .addComponent(txtclave)
                    .addComponent(txtcelular)
                    .addComponent(cmbTipoUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbTienda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnmodificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnimprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncerrar))
                    .addComponent(txtnombres)
                    .addComponent(txtapellidos)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId_TIPO_USUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtbuscar_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 394, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(txtbuscar_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrar)
                            .addComponent(btnmodificar)
                            .addComponent(btneliminar)
                            .addComponent(btncerrar)
                            .addComponent(btnimprimir)
                            .addComponent(btnReportar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId_TIPO_USUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
         try {
            if (txtdni.getText().length() > 0) {
                if (txtnombres.getText().length() > 0) {
                    if (txtapellidos.getText().length() > 0) {
                        if (txtdireccion.getText().length() > 0) {
                            if (txtcelular.getText().length() > 0) {
                                if (txtclave.getText().length() > 0) {

                                    Usuario oUsuario = new Usuario();
                                    UsuarioBD oUsuarioBD = new UsuarioBD();
                                    oUsuario.setuDni(txtdni.getText().toUpperCase().trim());
                                    oUsuario.setuNombre(txtnombres.getText().toUpperCase().trim());
                                    oUsuario.setuApellidos(txtapellidos.getText().toUpperCase().trim());
                                    oUsuario.setuDireccion(txtdireccion.getText().toUpperCase().trim());
                                    oUsuario.setuClave(txtclave.getText().toUpperCase().trim());
                                    oUsuario.setuCelular(txtcelular.getText().toUpperCase().trim());
                                    oUsuario.setuTipo(Integer.parseInt(txtId_TIPO_USUARIO.getText()));
                                    oUsuario.setTienda(cmbTienda.getSelectedItem().toString());

                                    boolean rpta = oUsuarioBD.modificarUsuario(oUsuario);
                                    if (rpta) {
                                        exito("Se modifico con exito");
                                        reportar_usuarios();
                                        limpiar();
                                    } else {
                                        error("Tiene problemas al modificar usuario");
                                    }

                                } else {
                                    advertencia("Ingrese clave");
                                    txtclave.requestFocus();
                                }

                            } else {
                                advertencia("Ingrese celular");
                                txtcelular.requestFocus();

                            }

                        } else {
                            advertencia("Ingrese direccion");
                            txtdireccion.requestFocus();
                        }

                    } else {
                        advertencia("Ingrese apellidos");
                        txtapellidos.requestFocus();
                    }

                } else {
                    advertencia("Ingrese nombres");
                    txtnombres.requestFocus();
                }

            } else {
                advertencia("Ingrese dni");
                txtdni.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
         try {
            if (txtdni.getText().length() > 0) {
                if (txtnombres.getText().length() > 0) {
                    if (txtapellidos.getText().length() > 0) {
                        if (txtdireccion.getText().length() > 0) {
                            if (txtcelular.getText().length() > 0) {
                                if (txtclave.getText().length() > 0) {

                                    Usuario oUsuario = new Usuario();
                                    UsuarioBD oUsuarioBD = new UsuarioBD();
                                    oUsuario.setuDni(txtdni.getText().toUpperCase().trim());
                                    oUsuario.setuNombre(txtnombres.getText().toUpperCase().trim());
                                    oUsuario.setuApellidos(txtapellidos.getText().toUpperCase().trim());
                                    oUsuario.setuDireccion(txtdireccion.getText().toUpperCase().trim());
                                    oUsuario.setuClave(txtclave.getText().toUpperCase().trim());
                                    oUsuario.setuCelular(txtcelular.getText().toUpperCase().trim());
                                    oUsuario.setuTipo(Integer.parseInt(txtId_TIPO_USUARIO.getText()));
                                    oUsuario.setTienda(cmbTienda.getSelectedItem().toString());

                                    boolean rpta = oUsuarioBD.registrarUsuarios(oUsuario);
                                    if (rpta) {
                                        exito("Se registro con exito");
                                        reportar_usuarios();
                                        limpiar();
                                    } else {
                                        error("Tiene problemas al registrar usuario");
                                    }

                                } else {
                                    advertencia("Ingrese clave");
                                    txtclave.requestFocus();
                                }

                            } else {
                                advertencia("Ingrese celular");
                                txtcelular.requestFocus();

                            }

                        } else {
                            advertencia("Ingrese direccion");
                            txtdireccion.requestFocus();
                        }

                    } else {
                        advertencia("Ingrese apellidos");
                        txtapellidos.requestFocus();
                    }

                } else {
                    advertencia("Ingrese nombres");
                    txtnombres.requestFocus();
                }

            } else {
                advertencia("Ingrese dni");
                txtdni.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cmbTipoUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoUsuarioItemStateChanged
        // TODO add your handling code here:
         if (evt.getStateChange() == ItemEvent.SELECTED) {
            String textoSeleccionado = (String) cmbTipoUsuario.getSelectedItem();

            if (textoSeleccionado.equals("SELECCIONAR")) {
                txtId_TIPO_USUARIO.setText("");
            } else {
                int i = cmbTipoUsuario.getSelectedIndex() -1;

                txtId_TIPO_USUARIO.setText("" + lista_tipo_usuario.get(i).getIdtipousuario());
            }

        }
    }//GEN-LAST:event_cmbTipoUsuarioItemStateChanged

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        try {
            if (txtdni.getText().length() > 0) {
                int aviso = JOptionPane.showConfirmDialog(rootPane, "Estas seguro de eliminar");
                if (aviso == 0) {
                    UsuarioBD oUsuarioBD = new UsuarioBD();

                    String dni = txtdni.getText();
                    boolean rpta = oUsuarioBD.eliminarUsuario(dni);
                    if (rpta) {
                        exito("Se elimino el usuario correctamente");
                        reportar_usuarios();
                        limpiar();
                        txtdni.requestFocus();
                    } else {
                        error("Tienes problemas para eliminar");
                    }
                }

            } else {
                error("Ingrese un dni para eliminar");
                txtdni.requestFocus();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void tabla_reporte_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_reporte_usuarioMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int fila_seleccionada = tabla_reporte_usuario.getSelectedRow();

            txtdni.setText(tabla_reporte_usuario.getValueAt(fila_seleccionada, 0).toString());
            txtnombres.setText(tabla_reporte_usuario.getValueAt(fila_seleccionada, 1).toString());
            txtapellidos.setText(tabla_reporte_usuario.getValueAt(fila_seleccionada, 2).toString());
            txtdireccion.setText(tabla_reporte_usuario.getValueAt(fila_seleccionada, 3).toString());
            txtclave.setText(tabla_reporte_usuario.getValueAt(fila_seleccionada, 4).toString());
            txtcelular.setText(tabla_reporte_usuario.getValueAt(fila_seleccionada, 5).toString());
            cmbTipoUsuario.setSelectedItem(tabla_reporte_usuario.getValueAt(fila_seleccionada, 6).toString());
            cmbTienda.setSelectedItem(tabla_reporte_usuario.getValueAt(fila_seleccionada, 7).toString());

        }
    }//GEN-LAST:event_tabla_reporte_usuarioMousePressed

    private void txtbuscar_apellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscar_apellidosKeyPressed
        // TODO add your handling code here:
        try {
            setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
            DefaultTableModel tabla_temporal;

            String apellidos = txtbuscar_apellidos.getText();

            UsuarioBD oUsuarioBD = new UsuarioBD();

            tabla_temporal = oUsuarioBD.buscarUsuario(apellidos);
            tabla_reporte_usuario.setModel(tabla_temporal);
            
            

            int cantLista = tabla_temporal.getRowCount();
            txtcantidad.setText("" + cantLista);

            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        } catch (Exception e) {
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            JOptionPane.showMessageDialog(null, "error al buscar_apellidos");
        }
                                                                                                                                                                                 
    }//GEN-LAST:event_txtbuscar_apellidosKeyPressed

    private void txtdniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || txtdni.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_txtdniKeyTyped

    private void txtdniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdniFocusGained
        // TODO add your handling code here:
        txtdni.setBackground(Color.yellow);
    }//GEN-LAST:event_txtdniFocusGained

    private void txtdniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdniFocusLost
        // TODO add your handling code here:
        txtdni.setBackground(Color.white);
    }//GEN-LAST:event_txtdniFocusLost

    private void txtnombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnombresFocusLost
        // TODO add your handling code here:
         txtnombres.setBackground(Color.white);
    }//GEN-LAST:event_txtnombresFocusLost

    private void txtnombresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnombresFocusGained
        // TODO add your handling code here:
         txtnombres.setBackground(Color.yellow);
    }//GEN-LAST:event_txtnombresFocusGained

    private void txtapellidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtapellidosFocusGained
        // TODO add your handling code here:
         txtapellidos.setBackground(Color.yellow);
    }//GEN-LAST:event_txtapellidosFocusGained

    private void txtapellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtapellidosFocusLost
        // TODO add your handling code here:
         txtapellidos.setBackground(Color.white);
    }//GEN-LAST:event_txtapellidosFocusLost

    private void txtdireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdireccionFocusGained
        // TODO add your handling code here:
         txtdireccion.setBackground(Color.yellow);
    }//GEN-LAST:event_txtdireccionFocusGained

    private void txtdireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdireccionFocusLost
        // TODO add your handling code here:
         txtdireccion.setBackground(Color.white);
    }//GEN-LAST:event_txtdireccionFocusLost

    private void txtclaveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtclaveFocusGained
        // TODO add your handling code here:
         txtclave.setBackground(Color.yellow);
    }//GEN-LAST:event_txtclaveFocusGained

    private void txtclaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtclaveFocusLost
        // TODO add your handling code here:
        txtclave.setBackground(Color.white);
    }//GEN-LAST:event_txtclaveFocusLost

    private void txtcelularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcelularFocusGained
        // TODO add your handling code here:
        txtcelular.setBackground(Color.yellow);
    }//GEN-LAST:event_txtcelularFocusGained

    private void txtcelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcelularFocusLost
        // TODO add your handling code here:
         txtcelular.setBackground(Color.white);
    }//GEN-LAST:event_txtcelularFocusLost

    private void txtcantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcantidadFocusGained
        // TODO add your handling code here:
         txtcantidad.setBackground(Color.yellow);
    }//GEN-LAST:event_txtcantidadFocusGained

    private void txtcantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcantidadFocusLost
        // TODO add your handling code here:
         txtcantidad.setBackground(Color.white);
    }//GEN-LAST:event_txtcantidadFocusLost

    private void cmbTipoUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbTipoUsuarioFocusGained
        // TODO add your handling code here:
        cmbTipoUsuario.setBackground(Color.yellow);
    }//GEN-LAST:event_cmbTipoUsuarioFocusGained

    private void cmbTipoUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbTipoUsuarioFocusLost
        // TODO add your handling code here:
         cmbTipoUsuario.setBackground(Color.white);
    }//GEN-LAST:event_cmbTipoUsuarioFocusLost

    private void cmbTiendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbTiendaFocusGained
        // TODO add your handling code here:
         cmbTienda.setBackground(Color.yellow);
    }//GEN-LAST:event_cmbTiendaFocusGained

    private void cmbTiendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbTiendaFocusLost
        // TODO add your handling code here:
        cmbTienda.setBackground(Color.white);
    }//GEN-LAST:event_cmbTiendaFocusLost

    private void txtdniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() ==KeyEvent.VK_ENTER) {
            txtnombres.requestFocus();
        }
    }//GEN-LAST:event_txtdniKeyPressed

    private void txtnombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() ==KeyEvent.VK_ENTER) {
            txtapellidos.requestFocus();
        }
    }//GEN-LAST:event_txtnombresKeyPressed

    private void txtapellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() ==KeyEvent.VK_ENTER) {
            txtdireccion.requestFocus();
        }
    }//GEN-LAST:event_txtapellidosKeyPressed

    private void txtdireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() ==KeyEvent.VK_ENTER) {
            txtclave.requestFocus();
        }
    }//GEN-LAST:event_txtdireccionKeyPressed

    private void txtclaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclaveKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() ==KeyEvent.VK_ENTER) {
            txtcelular.requestFocus();
        }
    }//GEN-LAST:event_txtclaveKeyPressed

    private void txtcelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcelularKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() ==KeyEvent.VK_ENTER) {
            cmbTipoUsuario.requestFocus();
        }
    }//GEN-LAST:event_txtcelularKeyPressed

    private void cmbTipoUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbTipoUsuarioKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() ==KeyEvent.VK_ENTER) {
            cmbTienda.requestFocus();
        }
    }//GEN-LAST:event_cmbTipoUsuarioKeyPressed

    private void txtcelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcelularKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (!Character.isDigit(c) || txtcelular.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_txtcelularKeyTyped

    private void txtclaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclaveKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || txtclave.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_txtclaveKeyTyped

    private void cmbTipoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbTipoUsuarioKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cmbTipoUsuarioKeyTyped

    private void cmbTiendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbTiendaKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cmbTiendaKeyTyped

    private void cmbTiendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbTiendaKeyPressed
        // TODO add your handling code here:
         if (evt.getExtendedKeyCode() ==KeyEvent.VK_ENTER) {
            btnRegistrar.requestFocus();
            btnRegistrar.doClick();
        }
    }//GEN-LAST:event_cmbTiendaKeyPressed

    private void txtnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (Character.isDigit(c) ) {
            evt.consume();
        }
    }//GEN-LAST:event_txtnombresKeyTyped

    private void txtapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (Character.isDigit(c) ) {
            evt.consume();
        }
    }//GEN-LAST:event_txtapellidosKeyTyped

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    private void txtbuscar_apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscar_apellidosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtbuscar_apellidosActionPerformed

    private void btnReportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportarActionPerformed
        // TODO add your handling code here:
         try {
            Conexion msyql=new Conexion();
            Connection cn=msyql.conectar();
            
            JasperReport reporte=null;
            
            String ruta = "src/CapaPresentacion/Reportes/Reporte_Usuario.jasper";
            reporte = (JasperReport) JRLoader.loadObjectFromFile(ruta);
            
            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, cn);
            JasperViewer jvmostrar=new JasperViewer(jprint,false);
            
            jvmostrar.setTitle("REPORTE DE USUARIO");
            jvmostrar.setVisible(true);
            jvmostrar.setExtendedState(6);
            
            jvmostrar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnReportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReportar;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JComboBox<String> cmbTienda;
    private javax.swing.JComboBox<String> cmbTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_reporte_usuario;
    private javax.swing.JTextField txtId_TIPO_USUARIO;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtbuscar_apellidos;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcelular;
    private javax.swing.JTextField txtclave;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtnombres;
    // End of variables declaration//GEN-END:variables
}
